version: '3.2'

services:
  php:
    volumes:
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
      - dip-data-sync:/var/www/html:nocopy

volumes:
  dip-data-sync:
    external: true
