version: '3.7'

services:
  php:
    build: ./.docker/php
    restart: always
    networks:
      dip-network:
        aliases:
          - php-fpm
    depends_on:
      - database
      - cache
    volumes:
      - .:/var/www/app
      - ./.docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    labels:
      - "SERVICE_IGNORE=true"

  nginx:
    build: ./.docker/nginx
    networks:
      - dip-network
    restart: always
    depends_on:
      - php
    ports:
      - "${SERVER_HTTP_PORT}:80"
    volumes:
      - .:/var/www/app
    labels:
      - "SERVICE_IGNORE=true"

  database:
    image: mariadb:10.5
    networks:
      - dip-network
    restart: always
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    labels:
      - "SERVICE_IGNORE=true"

  cache:
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - dip-network
    labels:
      - "SERVICE_IGNORE=true"

volumes:
  mariadb-data:

networks:
  dip-network:
